name: Deng,yonghao
description: iOS 开发


url: http://dengyonghao.github.io

baseurl: /dengyonghao

github: 'dengyonghao'

gaaccount: ''

disqus: 'dengyonghao'
comments: true

permalink: /:year/:month/:title
paginate: 3

highlighter: pygments
markdown: redcarpet
redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables", "with_toc_data"]

exclude: ['README.md', 'LICENSE']
